### ISSUE TITLE
clear() crashes

### ISSUE THREAD

**Issue by crusty-dave** [spacejam/sled#614]
When I populated a single table with about 6K entries, then I called clear(), it crashed.

I called it from within an actix-web handler, so that might be problematic.  I will try to spawn it as a thread when I get a chance to try it again.

The stack trace is in the attached text file.

Bug reports must include:
1. sled version 0.20.0
2. rustc version 1.33.0
3. operating system Windows 10
4. logs
[sled-crash.txt](https://github.com/spacejam/sled/files/3041919/sled-crash.txt)

**Comment by spacejam** [comment]
@crusty-dave thanks for submitting the issue, and for being so kind as to include the crash log :) In general workloads that use clear are undertested, so I'm more suspicious of my code than your usage of it. I should be able to give this a closer look later today

**Comment by crusty-dave** [comment]
@spacejam  I just did it again with only 998 entries and it was fine.  I think it crashed because I had called drop_tree() previously, which didn't seem to work.  I will keep you updated as I learn more.

**Comment by crusty-dave** [comment]
@spacejam I can consistently cause a crash at this point using the clear().

In the code snippet below, I populate the DB with JSON data, jv_res is a JsonValue.  I create 2000 entries like that and when I go to clear them, it hits the exception.

The documentation mentions small and large values and discusses using Arc with large values, is that something done under the hood or do I actually have to allocated and provide the Arc?  Perhaps this is related to my issue?  Each JasonValue represents about 500 characters.

`
                                    let jv_res = JMemoryDb::generate_session(&sess_template[..]);
                                    match jv_res {
                                        Ok(jv) => {
                                            if jv.has_key("ip") {
                                                let key_opt = jv["ip"].as_str();
                                                match key_opt {
                                                    Some(key) => {
                                                        match t.contains_key(key) {
                                                            Ok(present) => {
                                                                if !present {
                                                                    jinfo!("key {} val.len {}", key, jv.len());
                                                                    jinfo!("{}", jv);
                                                                    let jv_str = jv.to_string();
                                                                    let vv = jv_str.into_bytes();
                                                                    let db_key = key.as_bytes();
                                                                    let res = t.set(db_key, vv);
                                                                    match res {
                                                                        Ok(_vec) => {
                                                                            created += 1;
                                                                        },
                                                                        Err(_e) => {
                                                                            errors += 1;
                                                                        }
                                                                    }
                                                                } else {
                                                                    duplicates += 1;
                                                                }
                                                            },

`
[sled-crash2.txt](https://github.com/spacejam/sled/files/3046411/sled-crash2.txt)

**Comment by spacejam** [comment]
the Arc is created automatically when we can't inline keys and values over like 15 bytes or so. I've been trying to reproduce, and have occasionally been able to retrigger it but I don't have a reliable way of triggering the issue yet, so if you have any code that can trigger the bug more reliably I'd be grateful :]

**Comment by spacejam** [comment]
@crusty-dave I just fixed 2 issues that may be related to this issue. Would you be able to run your workload again on the current master? I'm curious if this issue is now fixed for you

**Comment by crusty-dave** [comment]
Sure, just let me know what I should put in Cargo.toml to pull it down?

I currently have the following:

`sled = "0.20"
`

**Comment by spacejam** [comment]
@crusty-dave I just pushed a new version that might fix it, try bumping sled to `"0.23"` - but just so you know, sled doesn't yet guarantee forward compatibility, and if you bump the minor version it might detect a previously written database file as being corrupt, so make sure you use a fresh file that you don't care about after upgrading.

Thanks for helping to track this down :)

**Comment by crusty-dave** [comment]
Is there a way to read the sled and schema versions so that I could auto-delete if different?

**Comment by crusty-dave** [comment]
@spacejam  It looks like I can't build with rustc 1.33 if I move sled to 0.23, there are some unstable features (I currently build with stable).  Once we get our internal toolchain moved to rustc 1.34 I will try again to see if 1.34 resolved those issues.

**Comment by crusty-dave** [comment]
I was finally able to build with rustc 1.34, I still see the crash (Windows 10).  I will see if I can come up with a test case for you to repro.

**Comment by spacejam** [comment]
@crusty-dave ahh damn. Well, I really appreciate you helping with a test case - it should hopefully be a quick fix once I can reproduce it
